package com.dong.green.dao.dataBase.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.dong.green.dao.dataBase.bean.User;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER".
*/
public class UserDao extends AbstractDao<User, Long> {

    public static final String TABLENAME = "USER";

    /**
     * Properties of entity User.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Member_name = new Property(1, String.class, "member_name", false, "MEMBER_NAME");
        public final static Property Member_phone = new Property(2, String.class, "member_phone", false, "MEMBER_PHONE");
        public final static Property Member_level = new Property(3, int.class, "member_level", false, "MEMBER_LEVEL");
        public final static Property Member_discount = new Property(4, String.class, "member_discount", false, "MEMBER_DISCOUNT");
    }


    public UserDao(DaoConfig config) {
        super(config);
    }
    
    public UserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"MEMBER_NAME\" TEXT," + // 1: member_name
                "\"MEMBER_PHONE\" TEXT," + // 2: member_phone
                "\"MEMBER_LEVEL\" INTEGER NOT NULL ," + // 3: member_level
                "\"MEMBER_DISCOUNT\" TEXT);"); // 4: member_discount
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String member_name = entity.getMember_name();
        if (member_name != null) {
            stmt.bindString(2, member_name);
        }
 
        String member_phone = entity.getMember_phone();
        if (member_phone != null) {
            stmt.bindString(3, member_phone);
        }
        stmt.bindLong(4, entity.getMember_level());
 
        String member_discount = entity.getMember_discount();
        if (member_discount != null) {
            stmt.bindString(5, member_discount);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, User entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String member_name = entity.getMember_name();
        if (member_name != null) {
            stmt.bindString(2, member_name);
        }
 
        String member_phone = entity.getMember_phone();
        if (member_phone != null) {
            stmt.bindString(3, member_phone);
        }
        stmt.bindLong(4, entity.getMember_level());
 
        String member_discount = entity.getMember_discount();
        if (member_discount != null) {
            stmt.bindString(5, member_discount);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public User readEntity(Cursor cursor, int offset) {
        User entity = new User( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // member_name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // member_phone
            cursor.getInt(offset + 3), // member_level
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4) // member_discount
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, User entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMember_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMember_phone(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setMember_level(cursor.getInt(offset + 3));
        entity.setMember_discount(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(User entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(User entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(User entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
